spring:
  application:
    name: v1-attachment-service
  profiles:
    active: ${PROFILE}
  config:
    import: ${CLOUD_CONFIG_IMPORT_URL:optional:configserver:https://api.xquare.app/cloud-config/}
  cloud:
    config:
      username: ${CLOUD_CONFIG_USERNAME}
      password: ${CLOUD_CONFIG_PASSWORD}

  servlet:
    multipart:
      max-file-size: ${multipart.file.size}
      max-request-size: ${multipart.request.size}

cloud:
  aws:
    credentials:
      access-key: ${s3.access}
      secret-key: ${s3.secret}
    s3:
      bucket: ${s3.bucket}
    region:
      static: ${s3.region}
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
